//
//  UserSavedItem.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class UserSavedItem: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _itemId: String?
    var _creationDate: NSNumber?
    var _distance: String?
    var _imageUrl: String?
    var _locationAddress: String?
    var _locationCategory: String?
    var _locationName: String?
    var _rating: String?
    var _updatedDate: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "makeadate-mobilehub-1183265318-UserSavedItem"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_itemId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_itemId" : "itemId",
               "_creationDate" : "creationDate",
               "_distance" : "distance",
               "_imageUrl" : "imageUrl",
               "_locationAddress" : "locationAddress",
               "_locationCategory" : "locationCategory",
               "_locationName" : "locationName",
               "_rating" : "rating",
               "_updatedDate" : "updatedDate",
        ]
    }
}
