//
//  UserSavedItems.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class UserSavedItems: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _locationName: String?
    var _distance: String?
    var _endDate: String?
    var _imageUrl: String?
    var _locationAddress: String?
    var _locationCategory: String?
    var _rating: String?
    var _startDate: String?
    var _updatedDate: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "makeadate-mobilehub-1183265318-UserSavedItems"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_locationName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_locationName" : "locationName",
               "_distance" : "distance",
               "_endDate" : "endDate",
               "_imageUrl" : "imageUrl",
               "_locationAddress" : "locationAddress",
               "_locationCategory" : "locationCategory",
               "_rating" : "rating",
               "_startDate" : "startDate",
               "_updatedDate" : "updatedDate",
        ]
    }
}
