# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Make A Date' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSMobileClient', '~> 2.6.13'
  # Pods for Make A Date

end
