# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Make A Date' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Auth Dependencies
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSUserPoolsSignIn', '~> 2.6.13'
  pod 'AWSAuthUI', '~> 2.6.13'

  # Analytics dependency
  pod 'AWSPinpoint', '~> 2.6.13'

  # NoSQL Data Dependencies
  pod 'AWSDynamoDB', '~> 2.6.5'

  # Location Picker dependency
  pod 'LocationPicker'

  # Pods for Make A Date

end
